[providers]
node = "20"
python = "3.11"

[phases.setup]
nixPkgs = ["nodejs_20", "python311", "gcc"]

[phases.install]
cmd = "npm install && cd custom-ai && pip install -r requirements.txt"

[phases.build]
cmd = "npm run build"

[start]
cmd = "cd custom-ai && python -m uvicorn main:app --host 0.0.0.0 --port 8000 & npm run start"